# Generated by Django 5.2.7 on 2026-10-03 04:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMediaProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='catalog.mediaitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Media Progress',
                'verbose_name_plural': 'User Media Progresses',
            },
        ),
        migrations.CreateModel(
            name='SeriesProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_season', models.PositiveIntegerField(default=1)),
                ('current_episode', models.PositiveIntegerField(default=0)),
                ('last_watched_episode_title', models.CharField(blank=True, default='', max_length=255)),
                ('progress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='series_progress', to='tracking.usermediaprogress')),
            ],
            options={
                'verbose_name': 'Series Progress',
                'verbose_name_plural': 'Series Progresses',
            },
        ),
        migrations.CreateModel(
            name='MangaProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_chapter', models.PositiveIntegerField(default=0)),
                ('current_volume', models.PositiveIntegerField(blank=True, null=True)),
                ('progress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manga_progress', to='tracking.usermediaprogress')),
            ],
            options={
                'verbose_name': 'Manga Progress',
                'verbose_name_plural': 'Manga Progresses',
            },
        ),
        migrations.CreateModel(
            name='GameProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hours_played', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Cumulative hours invested in this game.', max_digits=6)),
                ('completion_type', models.CharField(blank=True, choices=[('MAIN_STORY', 'Main Story'), ('MAIN_EXTRA', 'Main + Extra'), ('COMPLETIONIST', '100% Completionist')], max_length=20, null=True)),
                ('platform_played_on', models.CharField(blank=True, default='', max_length=100)),
                ('progress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_progress', to='tracking.usermediaprogress')),
            ],
            options={
                'verbose_name': 'Game Progress',
                'verbose_name_plural': 'Game Progresses',
            },
        ),
        migrations.CreateModel(
            name='UserMediaStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PLAN_TO_WATCH', 'Plan to Watch'), ('WATCHING', 'Watching'), ('WATCHED', 'Watched'), ('COMPLETED', 'Completed'), ('PLAN_TO_READ', 'Plan to Read'), ('READING', 'Reading'), ('BACKLOG', 'Backlog'), ('PLAYING', 'Playing'), ('FINISHED', 'Finished'), ('PAUSED', 'Paused'), ('DROPPED', 'Dropped / Abandoned')], db_index=True, max_length=30)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='catalog.mediaitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Media Status',
                'verbose_name_plural': 'User Media Statuses',
            },
        ),
        migrations.CreateModel(
            name='DiaryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logged_date', models.DateField(default=django.utils.timezone.now, help_text='Date the consumption session occurred. Editable.')),
                ('is_rewatch_or_replay', models.BooleanField(default=False, help_text='Flag indicating whether this session was a rewatch, re-read, or replay.')),
                ('session_notes', models.TextField(blank=True, default='', help_text="User's thoughts or quick notes for this specific consumption session.")),
                ('progress_snapshot', models.JSONField(blank=True, default=dict, help_text="Snapshot of progress at log time (e.g. {'season': 2, 'episode': 5} or {'session_hours': 2.5}).")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Immutable creation audit timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last controlled edit.')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_logs', to='catalog.mediaitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diary Log',
                'verbose_name_plural': 'Diary Logs',
                'ordering': ['-logged_date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-logged_date'], name='tracking_di_user_id_f4e464_idx'), models.Index(fields=['media_item'], name='tracking_di_media_i_417261_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='usermediaprogress',
            constraint=models.UniqueConstraint(fields=('user', 'media_item'), name='unique_user_media_progress'),
        ),
        migrations.AddIndex(
            model_name='usermediastatus',
            index=models.Index(fields=['user', 'status'], name='tracking_us_user_id_5bdefe_idx'),
        ),
        migrations.AddIndex(
            model_name='usermediastatus',
            index=models.Index(fields=['media_item'], name='tracking_us_media_i_8e6636_idx'),
        ),
        migrations.AddConstraint(
            model_name='usermediastatus',
            constraint=models.UniqueConstraint(fields=('user', 'media_item'), name='unique_user_media_status'),
        ),
    ]
