# Generated by Django 5.2.7 on 2026-10-03 04:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('MOVIE', 'Movie'), ('SERIES', 'TV Series'), ('MANGA', 'Manga / Manhwa'), ('GAME', 'Video Game')], db_index=True, help_text='Primary category format of this pop-culture media item.', max_length=20)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(help_text='Unique URL slug, formatted as {title-kebab-case}-{year}.', max_length=280, unique=True)),
                ('synopsis', models.TextField(blank=True, default='')),
                ('release_year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('poster_url', models.URLField(blank=True, default='', max_length=500)),
                ('backdrop_url', models.URLField(blank=True, default='', max_length=500)),
                ('tmdb_id', models.CharField(blank=True, help_text='Optional TMDb ID', max_length=50, null=True)),
                ('mal_id', models.CharField(blank=True, help_text='Optional MyAnimeList ID', max_length=50, null=True)),
                ('rawg_id', models.CharField(blank=True, help_text='Optional RAWG Game ID', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Item',
                'verbose_name_plural': 'Media Items',
                'ordering': ['-release_year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GameDetail',
            fields=[
                ('media_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='game_detail', serialize=False, to='catalog.mediaitem')),
                ('developer', models.CharField(blank=True, default='', max_length=255)),
                ('publisher', models.CharField(blank=True, default='', max_length=255)),
                ('platforms', models.JSONField(blank=True, default=list, help_text="Supported platforms, e.g. ['PC', 'PS5', 'Xbox', 'Switch'].")),
                ('average_story_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Estimated main story completion time in hours.', max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Game Detail',
                'verbose_name_plural': 'Game Details',
            },
        ),
        migrations.CreateModel(
            name='MangaDetail',
            fields=[
                ('media_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='manga_detail', serialize=False, to='catalog.mediaitem')),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('artist', models.CharField(blank=True, default='', max_length=255)),
                ('manga_type', models.CharField(choices=[('MANGA', 'Manga'), ('MANHWA', 'Manhwa'), ('MANHUA', 'Manhua'), ('WEBTOON', 'Webtoon')], default='MANGA', max_length=20)),
                ('status', models.CharField(choices=[('PUBLISHING', 'Publishing'), ('FINISHED', 'Finished'), ('HIATUS', 'On Hiatus')], default='PUBLISHING', max_length=20)),
                ('total_chapters', models.PositiveIntegerField(blank=True, help_text='Null if ongoing publication.', null=True)),
            ],
            options={
                'verbose_name': 'Manga Detail',
                'verbose_name_plural': 'Manga Details',
            },
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('media_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='movie_detail', serialize=False, to='catalog.mediaitem')),
                ('director', models.CharField(blank=True, default='', max_length=255)),
                ('runtime_minutes', models.PositiveIntegerField(blank=True, help_text='Runtime in minutes.', null=True)),
                ('studio', models.CharField(blank=True, default='', max_length=255)),
                ('ott_providers', models.JSONField(blank=True, default=list, help_text="List of streaming services (e.g. ['Netflix', 'Prime Video']).")),
            ],
            options={
                'verbose_name': 'Movie Detail',
                'verbose_name_plural': 'Movie Details',
            },
        ),
        migrations.CreateModel(
            name='SeriesDetail',
            fields=[
                ('media_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='series_detail', serialize=False, to='catalog.mediaitem')),
                ('creators', models.CharField(blank=True, default='', max_length=255)),
                ('total_seasons', models.PositiveIntegerField(default=1)),
                ('total_episodes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AIRING', 'Airing'), ('ENDED', 'Ended'), ('CANCELLED', 'Cancelled')], default='AIRING', max_length=20)),
                ('ott_providers', models.JSONField(blank=True, default=list, help_text='List of broadcast networks/streaming platforms.')),
            ],
            options={
                'verbose_name': 'Series Detail',
                'verbose_name_plural': 'Series Details',
            },
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='media_items', to='catalog.genre'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='media_items', to='catalog.tag'),
        ),
        migrations.AddIndex(
            model_name='mediaitem',
            index=models.Index(fields=['media_type', 'release_year'], name='catalog_med_media_t_302003_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaitem',
            index=models.Index(fields=['title'], name='catalog_med_title_f102d9_idx'),
        ),
    ]
