# Generated by Django 5.2.7 on 2026-10-03 05:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_key', models.SlugField(help_text="Canonical provider identifier (e.g. 'tmdb', 'anilist', 'jikan', 'rawg').", unique=True)),
                ('display_name', models.CharField(help_text="Human-readable title (e.g. 'TMDB', 'AniList', 'Jikan', 'RAWG').", max_length=100)),
                ('base_url', models.URLField(blank=True, default='', max_length=255)),
                ('attribution_text', models.TextField(blank=True, default='', help_text='Mandatory legal attribution notice required by provider terms.')),
                ('attribution_url', models.URLField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Toggle enabling or disabling integration with this provider.')),
            ],
            options={
                'verbose_name': 'External Provider',
                'verbose_name_plural': 'External Providers',
                'ordering': ['provider_key'],
            },
        ),
        migrations.CreateModel(
            name='ExternalMediaMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, help_text="The provider's unique ID for this media (e.g. TMDB movie ID, AniList media ID).", max_length=100)),
                ('external_url', models.URLField(blank=True, default='', help_text="Direct link to media page on the provider's platform.", max_length=500)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('source_updated_at', models.DateTimeField(blank=True, help_text='Timestamp when provider last updated this record, if reported.', null=True)),
                ('media_item', models.ForeignKey(help_text='The local DreamTeal media catalog record.', on_delete=django.db.models.deletion.CASCADE, related_name='external_mappings', to='catalog.mediaitem')),
                ('provider', models.ForeignKey(help_text='The external source provider.', on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='catalog.externalprovider')),
            ],
            options={
                'verbose_name': 'External Media Mapping',
                'verbose_name_plural': 'External Media Mappings',
                'indexes': [models.Index(fields=['provider', 'external_id'], name='catalog_ext_provide_f6f8a6_idx'), models.Index(fields=['media_item', 'provider'], name='catalog_ext_media_i_7f6073_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='unique_provider_external_id')],
            },
        ),
    ]
