# Generated by Django 5.2.7 on 2026-10-03 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_externalprovider_externalmediamapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='mal_id',
        ),
        migrations.RemoveField(
            model_name='mediaitem',
            name='rawg_id',
        ),
        migrations.RemoveField(
            model_name='mediaitem',
            name='tmdb_id',
        ),
    ]
