# Generated by Django 5.2.7 on 2026-10-03 04:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(help_text="Unique slug identifier (e.g., 'peak', 'loved_it', 'good_time', 'not_my_thing', 'skip').", unique=True)),
                ('display_name', models.CharField(help_text="Human-readable title (e.g. 'Loved It').", max_length=100)),
                ('icon', models.CharField(help_text="Visual icon symbol, emoji, or token (e.g. '⚡', '💎', '🍿', '🌙', '🛑').", max_length=50)),
                ('description', models.TextField(blank=True, default='', help_text='Editorial explanation of what this qualitative verdict signifies.')),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Flag to allow enabling/retiring badges gracefully without breaking historical reviews.')),
                ('sort_order', models.PositiveIntegerField(default=1, help_text='Display ordering sequence in picker modals and UI chips.')),
            ],
            options={
                'verbose_name': 'Reaction Definition',
                'verbose_name_plural': 'Reaction Definitions',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MediaReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_text', models.TextField(blank=True, default='', help_text='Written critique or qualitative impressions (Markdown supported).')),
                ('contains_spoilers', models.BooleanField(default=False, help_text='Flag controlling spoiler mask overlays in the UI.')),
                ('is_public', models.BooleanField(default=True, help_text='Visibility toggle (True = community visible, False = personal notes).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.mediaitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_reviews', to=settings.AUTH_USER_MODEL)),
                ('reaction', models.ForeignKey(blank=True, help_text='Qualitative verdict outcome badge. Strictly non-numeric.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='reviews.reactiondefinition')),
            ],
            options={
                'verbose_name': 'Media Review',
                'verbose_name_plural': 'Media Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['media_item', 'is_public'], name='reviews_med_media_i_01f525_idx'), models.Index(fields=['user', '-created_at'], name='reviews_med_user_id_d1e273_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'media_item'), name='unique_user_media_review')],
            },
        ),
    ]
